# Generated by Django 5.2.4 on 2025-08-17 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonne',
            fields=[
                ('id_abonne', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('numPolice', models.CharField(max_length=50, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id_mesure', models.AutoField(primary_key=True, serialize=False)),
                ('date_heure', models.DateTimeField()),
                ('debit_L_min', models.FloatField()),
                ('volume_L', models.FloatField()),
                ('pression_bar', models.FloatField(blank=True, null=True)),
                ('abonne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.abonne')),
            ],
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id_alerte', models.AutoField(primary_key=True, serialize=False)),
                ('type_alerte', models.CharField(choices=[('fuite', 'Fuite'), ('surconsommation', 'Surconsommation'), ('autre', 'Autre')], max_length=20)),
                ('message', models.TextField()),
                ('statut', models.CharField(choices=[('vu', 'Vu'), ('non_vu', 'Non vu')], default='non_vu', max_length=10)),
                ('date_alerte', models.DateTimeField(auto_now_add=True)),
                ('mesure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mesure')),
            ],
        ),
        migrations.CreateModel(
            name='Objectif',
            fields=[
                ('id_objectif', models.AutoField(primary_key=True, serialize=False)),
                ('type_objectif', models.CharField(choices=[('jour', 'Jour'), ('semaine', 'Semaine'), ('mois', 'Mois')], max_length=10)),
                ('volume_cible_L', models.FloatField()),
                ('abonne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.abonne')),
            ],
        ),
        migrations.CreateModel(
            name='Statistique',
            fields=[
                ('id_statistique', models.AutoField(primary_key=True, serialize=False)),
                ('periode_date', models.DateField()),
                ('type_periode', models.CharField(choices=[('jour', 'Jour'), ('semaine', 'Semaine'), ('mois', 'Mois')], max_length=10)),
                ('volume_total_L', models.FloatField()),
                ('volume_max_L', models.FloatField()),
                ('abonne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.abonne')),
            ],
        ),
    ]
